name: main

on:
  workflow_dispatch:

jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - run: npm i pnpm -g
      - run: pnpm install
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      - run: pnpm run fetch
      - run: |
          cd json
          npm version patch --no-git-tag-version
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          push-branch: main
          commit-message: "chore(icons): auto-update from Figma"
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
