name: Update Icons

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - run: npm i pnpm -g
      - run: pnpm install

      - name: Fetch icons from Figma
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        run: pnpm run fetch

      - name: Build Iconify JSON
        run: pnpm install && pnpm run build

      - name: Bump version
        working-directory: ./json
        run: npm version patch --no-git-tag-version

      - name: Publish to npm
        working-directory: ./json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
