name: Update Icons

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - run: npm i pnpm -g
      - run: pnpm install

      - name: Fetch icons from Figma
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        run: pnpm run fetch

      - name: Build Iconify JSON
        run: pnpm install && pnpm run build

      - name: Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: main
          commit-message: "chore(icons): auto-update from Figma"
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Publish to npm
        if: success()
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release
